---
######################### Prep hosts to run OpenShift Installer

- name: Step 004.1 - Host preparation for OpenShift 4 deployment
  hosts: bastions
  become: true
  gather_facts: False
  tags:
  - step004
  - step004.1
  tasks:
  - name: Call Role to provision OCP4 install host
    include_role:
      name: host-ocp4-provisioner

######################### Run OpenShift Installer

- name: Step 004.2 - Install OpenShift
  hosts: bastions
  gather_facts: false
  become: false
  tags:
  - step004
  - step004.2
  tasks:
  - name: Call Role to install OpenShift
    include_role:
      name: host-ocp4-installer

######################### Run Service Mesh Workloads

- name: Step 004.3 - Install workloads for Advanced SM ILT
  hosts: bastions
  gather_facts: false
  become: false
  tags:
  - step004
  - step004.3
  tasks:
  - name: Call role to install 3Scale Multitenant
    include_role:
      name: ocp4-workload-3scale-multitenant
