---
######################### Prep hosts to run OpenShift Installer

- name: Step 004.1 - Host preparation for OpenShift 4 deployment
  hosts: bastions
  become: true
  gather_facts: False
  tags:
    - step004
    - step004.1
  tasks:
  - name: Call Role to provision OCP4 install host
    include_role:
      name: host-ocp4-provisioner