- name: Step 003 Pre Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 003 Pre Software"

    - import_role:
        name: infra-local-create-ssh_key
      when: set_env_authorized_key | bool


- name: Configure all hosts with Repositories, Common Files and Set environment key
  hosts:
    - all:!windows
  become: true
  gather_facts: False
  tags:
    - common_tasks
  roles:
    - role: set-repositories
      when: repo_method is defined

    - role: common
      when: install_common | bool

    - role: set_env_authorized_key
      when: set_env_authorized_key | bool

- name: Configuring Bastion Hosts
  hosts: bastions
  become: true
  gather_facts: False
  roles:
    - role: bastion
      when: install_bastion | bool
    # use rpm packages in common instead.
    #- role: ansible-version-lock
  tags:
    - bastion_tasks
  tags:
    - step004
    - bastion_tasks

- name: Place Tower License from env_secret_vars on bastion
  hosts: bastions
  become: yes
  tags:
    - step003
    - place_tower_license_file
  tasks:
    - blockinfile:
        create: yes
        path: /root/tower_license.txt
        block: "{{tower_license}}"
      when: tower_license is defined

- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - presoftware_flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"
