---
- name: Step 000 Pre Infrastructure
  hosts:        localhost
  connection:   local
  become:       false
  gather_facts: false

  tags:
    - step001
    - pre_infrastructure

  tasks:

  - name: Call infra-local-create-ssh-key role
    when: set_env_authorized_key | bool
    import_role:
      name: infra-local-create-ssh_key
    tags:
      - generate_env_keys
