
- name: Install client and OpenShift Installer binaries
  import_tasks: install_installer.yml

- name: Install client and OpenShift Installer binaries
  import_tasks: generate.ocp.configs.yml

- name: Create deployinprogress file
  file:
    path: /tmp/deployinprogress
    state: touch

- pause:
- name: Run the installer
  tags:
  - run_installer
  command: openshift-install create cluster --dir=/home/{{ ansible_user }}/{{ cluster_name }}
  async: "{{ 2 * 60 * 60 }}"

- name: Fetch kube config
  fetch:
    flat: yes
    src: /home/{{ ansible_user }}/{{ cluster_name }}/auth/{{ item }}
    dest: "{{ hostvars.localhost.output_dir }}/{{ env_type }}_{{ guid }}_{{ item }}"
  loop:
    - kubeconfig
    - kubeadmin-password
