- name: Copy Tower License File
  get_url:
    url: http://www.opentlc.com/download/license.txt 
    dest: /root/license.txt
  tags:
      - tower-license-injector

- name: Add the tower license
  command: tower-cli setting modify LICENSE @/root/license.txt --insecure
  tags:
      - tower-license-injector

      
