---
# This should be include
- include_tasks: locate_template.yml

- set_fact:
    heat_template: "{{output_dir}}/{{ env_type }}.{{ guid }}.{{cloud_provider}}_cloud_template"
  when: heat_template is not defined

- name: Print heat_template
  debug:
    var: heat_template

- name: Print heat_template_src
  debug:
    var: heat_template_src

- name: AWS Generate heat Template
  template:
    src: "{{ heat_template_src }}"
    dest: "{{ heat_template }}"
  tags:
    - aws_infrastructure_deployment
    - gen_cf_template

######################### Copy CF Template to S3 if too big
- name: Stat heat template
  stat:
    path: "{{ heat_template }}"
  register: stat_template
  tags:
    - aws_infrastructure_deployment
    - gen_cf_template

- when:
    stat_template.stat.size > 51200
  tags:
    - aws_infrastructure_deployment
    - gen_cf_template
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"
  block:
    - name: Get user name
      command: aws iam get-user
      register: rget_user
      ignore_errors: yes

    # Bucket name must be globally unique. Use the userID to define the bucketname.
    # Otherwise when we use the code in another account it fails because the bucket
    # already exists.
    - set_fact:
        aws_account_user: "{{rget_user.stdout|from_json|json_query('User.UserId')}}"
      ignore_errors: yes

    - set_fact:
        bucket_templates: "heat-templates-{{aws_account_user|default('user')|lower}}"

    - name: Create bucket
      s3_bucket:
        name: "{{bucket_templates}}"
    - name: Copy Template to S3
      aws_s3:
        bucket: "{{bucket_templates}}"
        object: "{{ env_type }}.{{ guid }}.{{cloud_provider}}_cloud_template"
        src: "{{ heat_template }}"
        mode: put

######################### Validate CF Template

- name: validate heat template (local)
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"
  command: >-
    aws heat validate-template
    --region {{ aws_region_final | d(aws_region) | default(region) | default('us-east-1')}}
    --template-body file://{{ heat_template }}
  changed_when: false
  register: heat_validation
  until: heat_validation is succeeded
  retries: "{{ heat_retries }}"
  delay: 20
  tags:
    - aws_infrastructure_deployment
    - validate_cf_template
  when: stat_template.stat.size <= 51200

- name: validate heat template (S3)
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"
  command: >-
    aws heat validate-template
    --region {{ aws_region_final | d(aws_region) | default(region) | default('us-east-1')}}
    --template-url https://s3.amazonaws.com/{{bucket_templates}}/{{env_type}}.{{guid}}.{{cloud_provider}}_cloud_template
  changed_when: false
  register: heat_validation
  until: heat_validation is succeeded
  retries: "{{ heat_retries }}"
  delay: 20
  tags:
    - aws_infrastructure_deployment
    - validate_cf_template
  when: stat_template.stat.size > 51200

######################### Launch CF Template
