---
- hosts:
    - localhost
    - all
  connection: local
  gather_facts: no
  tags: packer
  tasks:
    - name: stats env_vars.yml and (legacy) env_secret_vars.yml
      stat:
        path: configs/{{ env_type }}/{{ item }}
      loop:
        - env_vars.yml
        - env_secret_vars.yml
      register: rstat_varfiles

    - name: Include vars files
      include_vars:
        file: "{{ item.stat.path }}"
      when: item.stat.exists
      loop: "{{ rstat_varfiles.results }}"
      loop_control:
        label: "{{ item._ansible_item_label | default(item) }}"
    - name: Set ANSIBLE_REPO_PATH
      set_fact:
        ANSIBLE_REPO_PATH: "{{playbook_dir}}"
        WORKDIR: "{{output_dir}}"

    - name: Set output_dir if not defined
      set_fact:
        output_dir: >-
          {{
          ANSIBLE_REPO_PATH + '/workdir' if ANSIBLE_REPO_PATH is defined
          else '/tmp/output_dir'
          }}

      when: output_dir is not defined

    - name: Stat output_dir
      stat:
        path: "{{ output_dir }}"
      register: rstat_output_dir

    - name: Create output_dir if it does not exists
      file:
        directory: "{{ output_dir }}"
      when: not rstat_output_dir.stat.exists
