- name: Step 00xxxxx post software
  hosts: support
  gather_facts: False
  become: yes
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: Step lab post software deployment
  hosts: bastions
  gather_facts: False
  become: yes
  tags:
    - opentlc_bastion_tasks
  tasks:

    - name: Copy Tower License File
      copy:
        content: "{{ tower_license | from_json }}"
        dest: /root/license.txt

    - name: Copy Openstack PEM key
      blockinfile:
        path: /root/.ssh/openstack.pem
        block: |
          {{ openstack_pem | b64decode }}
        owner: root
        group: root
        mode: 0400
        state: present
        create: yes

    - name: Copy Openstack Pub key
      blockinfile:
        path: /root/.ssh/openstack.pub
        block: |
          {{ openstack_pub | b64decode }}
        owner: root
        group: root
        mode: 0400
        state: present
        create: yes
#    - name: Install ansible
#      yum:
#       name: ansible
#       state: latest

- name: Post Tower configs
  hosts: towers[0]
  become: yes
  roles:
    - { role: "tower_demo", when: hostvars.localhost.deploy_tower_demo | d(false) | bool }

- name: Install Tower For Homework
  hosts: bastions
  become: yes
  roles:
    - { role: "install-tower", when: hostvars.localhost.deploy_tower_homework | d(false) | bool }

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
