---
- name: Step 00xxxxx software
  hosts: bastions[0]
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"
    # This probably needs to get removed.
    # - name: Place Tower License from env_secret_vars on bastion
    #   blockinfile:
    #     create: yes
    #     path: /root/tower_license.txt
    #     block: "{{tower_license}}"
    #   when: tower_license is defined
    - name: Copy Tower License File
      copy:
        content: "{{ tower_license | from_json }}"
        dest: /root/license.txt

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
