- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"

- import_playbook: "{{workdir_dir}}/linklight-networking/provisioner/teardown_lab.yml"
