- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

    
    
  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys

  tasks:
  - debug:
      msg: "Step 000 Pre Infrastructure"

  - name: Generate SSH keys when set_env_authorized_key
    block:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{output_dir}}/{{ env_authorized_key }}" -q -N ""
      args:
        creates: "{{output_dir}}/{{ env_authorized_key }}"

    - name: fix permission
      file:
        path: "{{output_dir}}/{{ env_authorized_key }}"
        mode: 0400

    - name: Generate SSH pub key
      shell: ssh-keygen -y -f "{{output_dir}}/{{ env_authorized_key }}" > "{{output_dir}}/{{ env_authorized_key }}.pub"
      args:
        creates: "{{output_dir}}/{{ env_authorized_key }}.pub"
    when: set_env_authorized_key

    # tested version on 2018-07-24 fc86de92080165b72906a1477e389cf0298bd499
    # - name: Clone Ansible linklight repo locally - specfic commit
    #git:
    #  repo: https://github.com/network-automation/linklight.git
    #  dest: "{{output_dir}}/linklight"
    #  version: fc86de92080165b72906a1477e389cf0298bd499
- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

    
    
  tags:
    - flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"

- import_playbook: "{{output_dir}}/linklight-networking/provisioner/provision_lab.yml"
  tags:
   - linklight_provision


- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  
  
  tags:
  - post_flight_check
  tasks:
  - debug:
      msg: "Post-Software checks completed successfully"
