- name: SSH config setup
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - create_ssh_config
  tasks:
  - debug:
     var: "{{hostvars}}"
  - name: Store bastion hostname as a fact
    set_fact:
      bastion_hostname: "{{ hostvars[ groups[ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') ].0 ]['ec2_ip_address'] }}"

  - name: Create empty local ssh config as defined by deploy_local_ssh_config_location
    file:
      dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_type }}_{{ guid }}_ssh_conf"
      state: touch

  - name: Add bastion proxy config to workdir ssh config file
    blockinfile:
      dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_type }}_{{ guid }}_ssh_conf"
      marker: "##### {mark} ADDED BASTION PROXY HOST {{ env_type }}-{{ guid }} ######"
      content: |
          Host {{ bastion_hostname }}
            Hostname {{ bastion_hostname }}
            IdentityFile ~/.ssh/{{ key_name }}.pem
            IdentitiesOnly yes
            User {{ remote_user }}
            ControlMaster auto
            ControlPath /tmp/%h-%r
            ControlPersist 5m
            StrictHostKeyChecking no
    tags:
      - bastion_proxy_config_main

  - name: Add all hosts to workdir ssh config file
    blockinfile:
      dest: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_type }}_{{ guid }}_ssh_conf"
      marker: "##### {mark} ADDED Node Proxy Config  {{ item }} {{ env_type }}-{{ guid }} ######"
      block: |
          Host {{ hostvars[item].ec2_ip_address }}
            Hostname {{ hostvars[item].ec2_ip_address }}
            User {{ remote_user }}
            IdentityFile ~/.ssh/{{ key_name }}.pem
            ProxyCommand ssh -F {{ inventory_dir }}/../workdir/{{ env_type }}_{{ guid }}_ssh_conf {{ remote_user }}@{{ bastion_hostname }} -W %h:%p
            StrictHostKeyChecking no
    with_items:
      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_master') | replace('-', '_')] }}"
      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_node') | replace('-', '_')] }}"
      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_support') | replace('-', '_')] }}"
      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '_infranode') | replace('-', '_')] }}"
    tags:
      - bastion_proxy_config_hosts
