---

- name: Build Openstack Environment
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:

    - name: Create SSH Keypair from existing key
      when: student.public_key is defined
      os_keypair:
        cloud: opentlc
        state: present
        name: "student_key"
        public_key: "{{ student.public_key }}"

    - name: Create SSH Keypair for user
      when: student.public_key is not defined
      os_keypair:
        cloud: opentlc
        state: present 
        name: "student_key"
      register: student.keypair       

    - name: Display private key if keypair was created
      when: student.keypair is defined
      debug:
        msg: "{{ student.keypair }}"

    - name: Generate Heat Template
      import_role:
        name: infra-osp-template-generate
      vars:
        heat_template_dest: "{{ heat_template_dest }}"

    - name: Deploy Heat Stack
      os_stack:
        name: "{{ guid }}"
        cloud: opentlc
        state: present
        template: "{{ heat_template_dest }}"
        parameters:
          guid: "{{ guid }}"
          keypair_name: "student_key"
      register: deployed_stack
