---

- name: Step 001.0 Obtain OSP Auth Token
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Get Token
      os_auth:
        auth:
          auth_url: http://www.osp.opentlc.com:5000
          username: "{{ osp_admin_user }}"
          password: "{{ osp_admin_password }}"
          project_name: admin
          project_domain_name: default
          user_domain_name: default
        region_name: RegionOne
    - name: Display Token
      debug:
        var: auth_token

