# vim: set ft=ansible
---
# Implement your Workload deployment tasks here
- name: determine deployed sets
  k8s_facts:
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets_out


#- name: determine the deployed AZ
#  shell: "oc get machineset -n openshift-machine-api -o jsonpath --template '{.items[0].spec.template.spec.providerSpec.value.placement.region}'"
#  register: deployed_az
#
- name: register list of machinesets
  shell: "oc get machineset -n openshift-machine-api -o name"
  register: infra_machineset_exists
#
# stdout will have the word infra if there's already an infra machineset
# if there is one, we don't create any

- name: create infra machineset(s)
  script: files/infra.sh {{ machinesets_out.resources[0].spec.template.spec.providerSpec.value.placement.region }}
  when: '"infra" not in infra_machineset_exists.stdout'

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool